#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     C1,             sensorNone)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
task main()
{
	while (true)
	{
		bFloatDuringInactiveMotorPWM = false;
		getJoystickSettings(joystick);
		motor[motorA] = joystick.joy1_y2; //Main drive motor
		motor[motorB] = -joystick.joy1_y1; //Main drive motor reversed
		if(abs(joystick.joy1_y2)>5){
			motor[motorA] = joystick.joy1_y2;
		}
		else{
			motor[motorA] = 0;
		}
		if(abs(joystick.joy1_y1)>5){
			motor[motorB] = -joystick.joy1_y1;
		}
		else{
			motor[motorA] = 0;
		}
	}
}
